### ISSUE TITLE
Auto-add public security level when missing

### ISSUE THREAD

**Issue by Mustek** [Mojira/ArisaJS#1]
KV location: fields.security

**When applied:**

```
"security": {
"self": "https://bugs.mojang.com/rest/api/2/securitylevel/10317",
"id": "10317",
"description": "Viewable by everyone",
"name": "Minecraft - Public"
},
```

**When missing:**
Object is not present

Security ID is not the same across projects, must be obtained during the project updating processes.
To fetch: api/2/project/{projectKeyOrId}/securitylevel
To set: ISSUE.fields.security (see editmeta)

**Comment by Mustek** [comment]
Done partially, still needs some changes to the core to allow editing of closed issues.

**Comment by urielsalis** [comment]
Moved to arisa-kt
