### ISSUE TITLE
Prevent users from publishing their session id

### ISSUE THREAD

**Issue by Marcono1234** [Mojira/ArisaJS#12]
Even though the launcher and the client were changed to not include the session id anymore, there are still people playing with old launchers old versions of the game (or the new launcher does not censor it?).

It would be good if Arisa could prevent people from

- putting the session id in the description
- writing the session id in a comment
- attaching a log file which contains the session id

The log line would have the prefix `(Session ID is` and would be `(Session ID is <censored>)` if it was censored by the old Java launcher.

**Comment by urielsalis** [comment]
Moved to arisa-kt
