### ISSUE TITLE
Arisa reopens an AR ticket when someone else than the reporter updates the report

### ISSUE THREAD

**Issue by violine1101** [Mojira/ArisaJS#14]
Example: [MC-142092](https://bugs.mojang.com/browse/MC-142092). The report was reopened when it was moved by me.

**Comment by Pokechu22** [comment]
Also includes adding a linked issue (including relates to).

**Comment by bemoty** [comment]
according to [L36](https://github.com/mojira/arisa-js/blob/master/checks/ModuleReopenAwaiting.js#L36) and [L45](https://github.com/mojira/arisa-js/blob/master/checks/ModuleReopenAwaiting.js#L45), there actually is a check if the updating user is also the reporter of the report before reopening it, so this seems more like a bug to me.

**Comment by urielsalis** [comment]
This is now the intended logic in arisa-kt
