### ISSUE TITLE
Arisa sometimes spams warnings when removing unreleased versions

### ISSUE THREAD

**Issue by violine1101** [Mojira/ArisaJS#16]
Examples:
* [MC-157823](https://bugs.mojang.com/browse/MC-157823) (comments are restricted to helper)
* [MC-158260](https://bugs.mojang.com/browse/MC-158260) (comments are restricted to helper)
* [MC-158261](https://bugs.mojang.com/browse/MC-158261) (private)
* [MC-138211](https://bugs.mojang.com/browse/MC-138211) (comments are restricted to helper)

It seems like this happens since Arisa just posts a comment, but does not actually remove the unreleased version.

This could also be fixed by remembering (or checking) whether Arisa has sent a warning on that ticket during the last 30 minutes, and if so, prevent it from posting a comment. This would also prevent Arisa from spamming the same comment over and over again when the reporter of the ticket doesn't get the message.

**Comment by urielsalis** [comment]
Arisa-kt doesnt run multiple times in the same ticket now
