### ISSUE TITLE
Resolution of empty / template / crash issues

### ISSUE THREAD

**Issue by Kumasasa** [Mojira/ArisaJS#2]
- Empty issues like https://bugs.mojang.com/browse/MC-100121 --> **Incomplete**
- "Put the summary of the bug"-only issues like https://bugs.mojang.com/browse/MC-100158   or https://bugs.mojang.com/browse/MC-22644 --> **Incomplete**
- "Report bug button but no attachment" like https://bugs.mojang.com/browse/MC-100122 -> **Awaiting Response**

**Comment by Kumasasa** [comment]
Resolution text for "Report bug button but no attachment":
`Please attach the crash report ({{[minecraft|http://hopper.minecraft.net/help/finding-minecraft-data-folder]/crash-reports/crash-<DATE>-client.txt}}), otherwise we can not diagnose this issue.\r\nFor technical support please use the [Mojang Support Center|http://help.mojang.com/customer/portal/articles/364794-where-can-i-find-more-help-and-technical-support-].`

**Comment by Kumasasa** [comment]
Hehe, the link to crash report could be changed to 
`file://C:\Users\<arisa-inserts-jira-reporter-name>\AppData\Roaming\.minecraft\crash-reports\crash-<arisa-inserts-current-date-minus-10-seconds>-client.txt`
Will be dead-on in 90% of all reports...

**Comment by Mustek** [comment]
And done.
