### ISSUE TITLE
Arisa no longer reopens tickets when they are updated by something other than a comment

### ISSUE THREAD

**Issue by violine1101** [Mojira/ArisaJS#21]
This does not happen if the last comment is made by the reporter.

Caused by 8b3ce30b6b9d44dcd847dfcf0a67bf980f33f811.

Code analysis:
```
if(!updateByCommentUpdate && commentAuthor == creator) issue.reopen();
```
This only reopens the ticket if it's not a comment update (comment updates are handled earlier) the last comment is made by the creator of the ticket.

Don't know if there's a good way to solve that issue. You don't seem to be able to get the user who actually updated the ticket.

**Comment by bemoty** [comment]
the entire check for reopening AR reports seems very hacky — does anyone know what a "comment update" is and why there are two checks for it?

**Comment by violine1101** [comment]
"Comment update" just means that the reporter left a comment without updating the ticket.

As for why there's two checks for it: You added the second check, didn't you? (Edit: Ah, seems like you only added the check for the user. Didn't parse that correctly.)

Also, it might be possible to query the history of a ticket to check who was the last person to update it. Haven't investigated that though.

**Comment by urielsalis** [comment]
Fixed by arisa-kt
