### ISSUE TITLE
Close tickets referring to MCL-6550 automatically

### ISSUE THREAD

**Issue by violine1101** [Mojira/ArisaJS#25]
It would be great if the bot would automatically close tickets that refer to [MCL-6550](https://bugs.mojang.com/browse/MCL-6550). That could be done by checking whether the ticket's summary, environment or description contain either `not responding` or `-805306369`.

I tried implementing it myself but got too overwhelmed with Arisa's infrastructure; there's `ModuleCrash` but that only checks the ticket's attachments. Additionally, currently it doesn't seem to be possible to run the bot in demo mode (i.e., without actually commenting or trying to resolve).

**Comment by urielsalis** [comment]
Moved to arisa-kt
