### ISSUE TITLE
Arisa does not comment anymore when removing future versions

### ISSUE THREAD

**Issue by Marcono1234** [Mojira/ArisaJS#29]
It looks like Arisa does not comment anymore when removing future versions (neither for MC nor for MCPE).
This can be problematic because the reporter might not notice the removal of the future version and addition of the latest version causing the wrong affected version to be set.

Example: https://bugs.mojang.com/browse/MC-172695

Maybe related to #16?

**Comment by urielsalis** [comment]
Fixed in arisa-kt
