### ISSUE TITLE
Activate Arisa for other projects (WEB, REALMS)

### ISSUE THREAD

**Issue by Marcono1234** [Mojira/ArisaJS#30]
It might be quite useful if Arisa was active and would reopen "Awaiting Response" reports for the projects WEB and REALMS.

However, @urielsalis mentioned that when he tried activating it there were failures.
And since there are not that many reports for these projects it is not that dramatic if Arisa is not active for them yet.

**Comment by urielsalis** [comment]
Done in arisa-kt
