### ISSUE TITLE
Automatic version updating with duplicates

### ISSUE THREAD

**Issue by CubeTheThird** [Mojira/ArisaJS#4]
Would be nice if, when marking a report as a duplicate of another, if the parent report could inherit all (valid) affected versions from the child, provided that the parent report is open or reopened.

**Comment by Mustek** [comment]
Possible, but wouldn't it be better if it were to just inherit the latest version?

**Comment by CubeTheThird** [comment]
Not necessarily. Someone might report a duplicate using an older version, as sometimes several versions are available, particularly when snapshots are around.

**Comment by Kumasasa** [comment]
+1 for all valid versions

**Comment by Mustek** [comment]
Define valid versions.

**Comment by CubeTheThird** [comment]
Affected versions that are not future releases, and that are still an option to select from current versions.

**Comment by urielsalis** [comment]
Moved to arisa-kt
