### ISSUE TITLE
Automatically updating report priority if it is empty

### ISSUE THREAD

**Issue by bemoty** [Mojira/ArisaJS#8]
Moving a report from any project to WEB without updating the priority causes the priority field of the report to stay empty. Arisa could set this field to the default "Minor" priority if it is empty.

See [`project = WEB AND priority = EMPTY`](https://bugs.mojang.com/issues/?jql=project%20%3D%20WEB%20AND%20priority%20%3D%20EMPTY).

**Comment by urielsalis** [comment]
Moved to arisa-kt
